name: "static analysis"

on: ["pull_request", "push"]

jobs:
  static-analysis:
    name: "static analysis"
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest']
        hhvm: ['4.113', '4.114', '4.115']
        dependencies: ['highest', 'locked']

    steps:
      - name: "checkout"
        uses: "actions/checkout@v2"

      - name: "installing hhvm"
        uses: "azjezz/setup-hhvm@v1"
        with:
          version: ${{ matrix.hhvm }}

      - name: "installing dependencies"
        uses: "ramsey/composer-install@v1"
        with:
          dependency-versions: ${{ matrix.dependencies }}
          composer-options: "${{ matrix.composer-options }}"

      - name: "dumping autoloader"
        run: "hhvm vendor/bin/hh-autoload"

      - name: "running static analysis"
        run: "hh_client"

      - name: "checking coding standards"
        run: "hhvm vendor/bin/hhast-lint"
